
version: 2

models:
  - name: ingest
    description: "A starter dbt model"
    columns:
      - name: a
        description: "neat, a table with two integers init"
        tests:
          - not_null
      - name: b
        tests:
          - not_null

  - name: second
    description: "It just kind of spits out the same stuff in ingest"
    columns:
      - name: a
        description: "The primary key for this table"
        tests:
          - not_null
      - name: b
        tests:
          - not_null